CREATE TABLE IF NOT EXISTS here_onces (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    note VARCHAR NOT NULL,
    photo_ids VARCHAR[] NOT NULL,
    created TIMESTAMPTZ NOT NULL
);
